### PR TITLE
Format rate in s/it when rate is < 1

### PR DESCRIPTION
**Pull request by elephantum**
For slow running iterations it's much more informative to see `rate:120s/it` than `rate:0it/s`

### CODE REVIEW

**Review by adyotag — APPROVED** [review]
Thank you for your edits. This was incredibly helpful for my application, where the iterations take a very long time.

**Comment by elephantum** [comment]
Hey, @miohtama any chance you can review and merge this PR?

**Review by adyotag — APPROVED** [review]

**Comment by miohtama** [comment]
Thank you. Merged. 

Sorry for late response time. Unfortunately I do not follow individual issues due to large number of notifications I am receiving from Github.

**Comment by miohtama** [comment]
Released in 0.2 https://pypi.org/project/tqdm-loggable/

**Comment by elephantum** [comment]
@miohtama yay, thanks!

**Pull request merged**
